recipe/meta.yaml
@t-sommer is the original maintainer of fmpy.
=> Add t-sommer to maintainers

recipe/meta.yaml
=> Bump version to 0.2.19

recipe/build_pkg.bat, recipe/meta.yaml
=> Bump version to 0.2.21 and install from PyPI

recipe/meta.yaml
=> Bump version to 0.2.22

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-osx.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.6.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .ci_support/osx_64_python3.6.____cpython.yaml, .ci_support/osx_64_python3.7.____cpython.yaml, .ci_support/osx_64_python3.8.____cpython.yaml, .ci_support/osx_64_python3.9.____cpython.yaml, .ci_support/win_64_python3.6.____cpython.yaml, .ci_support/win_64_python3.7.____cpython.yaml, .ci_support/win_64_python3.8.____cpython.yaml, .ci_support/win_64_python3.9.____cpython.yaml, README.md, recipe/build_base.bat, recipe/build_base.sh, recipe/meta.yaml
=> Bump version to 0.2.24

.ci_support/linux_64_python3.6.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, recipe/meta.yaml
=> Bump version to 0.2.25

.azure-pipelines/azure-pipelines-linux.yml, .ci_support/linux_64_python3.6.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, recipe/meta.yaml
=> Bump version to 0.2.26

.scripts/build_steps.sh, .scripts/logging_utils.sh, .scripts/run_docker_build.sh, .scripts/run_osx_build.sh, LICENSE.txt, README.md, recipe/meta.yaml
@conda-forge-admin please rerender
=> Bump version to 0.3.0

.azure-pipelines/azure-pipelines-linux.yml, .azure-pipelines/azure-pipelines-win.yml, .ci_support/linux_64_python3.10.____cpython.yaml, .ci_support/linux_64_python3.7.____cpython.yaml, .ci_support/linux_64_python3.8.____cpython.yaml, .ci_support/linux_64_python3.9.____cpython.yaml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, recipe/meta.yaml
@conda-forge-admin please rerender
=> Bump version to 0.3.4

recipe/meta.yaml
@conda-forge-admin please rerender
=> Bump version to 0.3.5

recipe/meta.yaml
=> Bump version to 0.3.7

README.md, recipe/meta.yaml
=> Bump version to 0.3.8

recipe/meta.yaml
=> Bump version to 0.3.9

.azure-pipelines/azure-pipelines-win.yml, .circleci/config.yml, recipe/meta.yaml
=> Bump version to 0.3.10

.azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, LICENSE.txt, build-locally.py, recipe/meta.yaml
=> Bump version to 0.3.11

.azure-pipelines/azure-pipelines-osx.yml, recipe/meta.yaml
=> Bump version to 0.3.12

recipe/meta.yaml
=> Bump version to 0.3.13

.azure-pipelines/azure-pipelines-win.yml, recipe/meta.yaml
=> Bump version to 0.3.14

.azure-pipelines/azure-pipelines-win.yml, .scripts/build_steps.sh, .scripts/run_osx_build.sh, README.md, recipe/meta.yaml
=> Bump version to 0.3.15

recipe/meta.yaml
=> Bump version to 0.3.20
